<?php
require('./connection.php');
$result=["c"=>true,"s"=>true];
if(!$con){
    $result['c']=false;
}else{
    $q=mysqli_query($con,"select * from colleges");
    if(!$q){
        $result["s"]=false;
    }else{
        $res=["name"=>array(),"address"=>array()];
        while($row=mysqli_fetch_assoc($q)){
            $res["name"][]=$row["name"];
            $res["address"][]=$row["address"];
        }
        $result["res"]=$res;
    }
}
mysqli_close($con);
$result=json_encode($result);
print_r($result);
?>